name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu, i686-unknown-linux-musl, mips-unknown-linux-gnu, mips64-unknown-linux-gnuabi64, mips64el-unknown-linux-gnuabi64, mipsel-unknown-linux-gnu, powerpc-unknown-linux-gnu, powerpc64-unknown-linux-gnu, powerpc64le-unknown-linux-gnu,           arm-unknown-linux-gnueabi          ,x86_64-unknown-linux-gnu           ,x86_64-unknown-linux-musl]
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
    - name: Build target
      uses: actions-rs/cargo@v1
      with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
    - name: Package
      shell: bash
      run: |
          cd target/${{ matrix.target }}/release
          ls
          tar czvf ../../../decompress-${{ matrix.target }}.tar.gz decompress
          cd -
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
          files: 'decompress*'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
